const name = require('./names')
const sayHi = require('./mynames')
const update = require('./2-alternative-flavour')
require('./addvalue')
console.log(update)
sayHi('susan')
sayHi(name.peter)
sayHi(name.john)
